package com.big.web.b2b_big2.flight.odr.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-10-13T10:55:29.358+07:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "Service1Soap")
@XmlSeeAlso({ObjectFactory.class})
public interface Service1Soap {

    @WebResult(name = "ConfirmBookingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConfirmBooking", targetNamespace = "http://tempuri.org/", className = "com.big.web.b2b_big2.flight.odr.ws.ConfirmBooking")
    @WebMethod(operationName = "ConfirmBooking", action = "http://tempuri.org/ConfirmBooking")
    @ResponseWrapper(localName = "ConfirmBookingResponse", targetNamespace = "http://tempuri.org/", className = "com.big.web.b2b_big2.flight.odr.ws.ConfirmBookingResponse")
    public com.big.web.b2b_big2.flight.odr.ws.BookingFlight confirmBooking(
        @WebParam(name = "BookingCode", targetNamespace = "http://tempuri.org/")
        java.lang.String bookingCode
    );

    @WebResult(name = "runODRLionAirResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "runODRLionAir", targetNamespace = "http://tempuri.org/", className = "com.big.web.b2b_big2.flight.odr.ws.RunODRLionAir")
    @WebMethod(action = "http://tempuri.org/runODRLionAir")
    @ResponseWrapper(localName = "runODRLionAirResponse", targetNamespace = "http://tempuri.org/", className = "com.big.web.b2b_big2.flight.odr.ws.RunODRLionAirResponse")
    public java.lang.String runODRLionAir(
        @WebParam(name = "origin", targetNamespace = "http://tempuri.org/")
        java.lang.String origin,
        @WebParam(name = "dest", targetNamespace = "http://tempuri.org/")
        java.lang.String dest,
        @WebParam(name = "departDate", targetNamespace = "http://tempuri.org/")
        java.lang.String departDate,
        @WebParam(name = "passenger", targetNamespace = "http://tempuri.org/")
        java.lang.String passenger
    );

    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "com.big.web.b2b_big2.flight.odr.ws.HelloWorld")
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "com.big.web.b2b_big2.flight.odr.ws.HelloWorldResponse")
    public java.lang.String helloWorld();

    @WebResult(name = "CommitBookingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CommitBooking", targetNamespace = "http://tempuri.org/", className = "com.big.web.b2b_big2.flight.odr.ws.CommitBooking")
    @WebMethod(operationName = "CommitBooking", action = "http://tempuri.org/CommitBooking")
    @ResponseWrapper(localName = "CommitBookingResponse", targetNamespace = "http://tempuri.org/", className = "com.big.web.b2b_big2.flight.odr.ws.CommitBookingResponse")
    public com.big.web.b2b_big2.flight.odr.ws.BookingFlight commitBooking(
        @WebParam(name = "BookingId", targetNamespace = "http://tempuri.org/")
        java.lang.String bookingId
    );

    @WebResult(name = "updateScheduleResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "updateSchedule", targetNamespace = "http://tempuri.org/", className = "com.big.web.b2b_big2.flight.odr.ws.UpdateSchedule")
    @WebMethod(action = "http://tempuri.org/updateSchedule")
    @ResponseWrapper(localName = "updateScheduleResponse", targetNamespace = "http://tempuri.org/", className = "com.big.web.b2b_big2.flight.odr.ws.UpdateScheduleResponse")
    public java.lang.String updateSchedule(
        @WebParam(name = "origin", targetNamespace = "http://tempuri.org/")
        java.lang.String origin,
        @WebParam(name = "dest", targetNamespace = "http://tempuri.org/")
        java.lang.String dest,
        @WebParam(name = "departDate", targetNamespace = "http://tempuri.org/")
        java.lang.String departDate,
        @WebParam(name = "airline", targetNamespace = "http://tempuri.org/")
        java.lang.String airline
    );

    @WebResult(name = "runODRSriwijayaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "runODRSriwijaya", targetNamespace = "http://tempuri.org/", className = "com.big.web.b2b_big2.flight.odr.ws.RunODRSriwijaya")
    @WebMethod(action = "http://tempuri.org/runODRSriwijaya")
    @ResponseWrapper(localName = "runODRSriwijayaResponse", targetNamespace = "http://tempuri.org/", className = "com.big.web.b2b_big2.flight.odr.ws.RunODRSriwijayaResponse")
    public java.lang.String runODRSriwijaya(
        @WebParam(name = "origin", targetNamespace = "http://tempuri.org/")
        java.lang.String origin,
        @WebParam(name = "dest", targetNamespace = "http://tempuri.org/")
        java.lang.String dest,
        @WebParam(name = "departDate", targetNamespace = "http://tempuri.org/")
        java.lang.String departDate,
        @WebParam(name = "passenger", targetNamespace = "http://tempuri.org/")
        java.lang.String passenger
    );

    @WebResult(name = "getBookingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getBooking", targetNamespace = "http://tempuri.org/", className = "com.big.web.b2b_big2.flight.odr.ws.GetBooking")
    @WebMethod(action = "http://tempuri.org/getBooking")
    @ResponseWrapper(localName = "getBookingResponse", targetNamespace = "http://tempuri.org/", className = "com.big.web.b2b_big2.flight.odr.ws.GetBookingResponse")
    public com.big.web.b2b_big2.flight.odr.ws.FindBookingResponseData getBooking(
        @WebParam(name = "criteria", targetNamespace = "http://tempuri.org/")
        java.lang.String criteria
    );
}
