CREATE TABLE APP_USER
(
  ID                   NUMBER(19)               NOT NULL,
  ACCOUNT_EXPIRED      NUMBER(1)                NOT NULL,
  ACCOUNT_LOCKED       NUMBER(1)                NOT NULL,
  ADDRESS              VARCHAR2(150 CHAR),
  CITY                 VARCHAR2(50 CHAR),
  COUNTRY              VARCHAR2(100 CHAR),
  POSTAL_CODE          VARCHAR2(15 CHAR),
  PROVINCE             VARCHAR2(100 CHAR),
  CREDENTIALS_EXPIRED  NUMBER(1)                NOT NULL,
  EMAIL                VARCHAR2(255 CHAR)       NOT NULL,
  ACCOUNT_ENABLED      NUMBER(1),
  FIRST_NAME           VARCHAR2(50 CHAR)        NOT NULL,
  LAST_NAME            VARCHAR2(50 CHAR)        NOT NULL,
  PASSWORD             VARCHAR2(255 CHAR)       NOT NULL,
  PASSWORD_HINT        VARCHAR2(255 CHAR),
  PHONE_NUMBER         VARCHAR2(255 CHAR),
  USERNAME             VARCHAR2(50 CHAR)        NOT NULL,
  VERSION              NUMBER(10),
  WEBSITE              VARCHAR2(255 CHAR)
)
;

ALTER TABLE APP_USER ADD (
  PRIMARY KEY
 (ID)
    USING INDEX ,
  UNIQUE (EMAIL)
    USING INDEX 
,
  UNIQUE (USERNAME)
    USING INDEX 
);
