CREATE TABLE BOOKING_FLIGHT_SCHEDULE
(
  ID                 VARCHAR2(40 BYTE),
  BOOKING_FLIGHT_ID  VARCHAR2(40 BYTE),
  DEPARTURE          VARCHAR2(5 BYTE),
  ARRIVAL            VARCHAR2(5 BYTE),
  DEP_TIME           DATE,
  ARRIVAL_TIME       DATE,
  FLIGHTNUM          VARCHAR2(15 BYTE),
  CLASS_NAME         VARCHAR2(1 BYTE),
  LASTUPDATE         DATE
)
;

CREATE UNIQUE INDEX BOOKING_FLIGHT_SCHEDULE_PK ON BOOKING_FLIGHT_SCHEDULE
(ID)
LOGGING;

ALTER TABLE BOOKING_FLIGHT_SCHEDULE ADD (
  CONSTRAINT BOOKING_FLIGHT_SCHEDULE_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
);
