CREATE TABLE FLIGHTAVAILSEAT
(
  FLIGHTAVAILID  VARCHAR2(40 BYTE),
  FLIGHTNUM      VARCHAR2(30 BYTE),
  ORIGIN         VARCHAR2(5 BYTE),
  DESTINATION    VARCHAR2(5 BYTE),
  DEP_TIME       DATE,
  ARR_TIME       DATE,
  AIRLINES       VARCHAR2(40 BYTE),
  ISTRANSIT      CHAR(1 BYTE),
  DEPARTURE      VARCHAR2(5 BYTE),
  ARRIVAL        VARCHAR2(5 BYTE),
  CURRENCY       CHAR(10 BYTE),
  AGENT_ID       NUMBER,
  CREATED_DATE   DATE                           DEFAULT sysdate
)
;

CREATE UNIQUE INDEX FLIGHTAVAILSEAT_PK ON FLIGHTAVAILSEAT
(FLIGHTAVAILID)
;

ALTER TABLE FLIGHTAVAILSEAT ADD (
  CONSTRAINT FLIGHTAVAILSEAT_PK
 PRIMARY KEY
 (FLIGHTAVAILID)
    USING INDEX 
);
