CREATE TABLE FLIGHT_CLASS_FARE
(
  CLASS_FARE_ID     NUMBER,
  FLIGHTAVAILID     VARCHAR2(40 BYTE),
  CLASS_NAME        CHAR(1 BYTE),
  CLASS_AVAIL_SEAT  NUMBER,
  CLASS_RATE        NUMBER,
  BASIC_RATE        NUMBER,
  TAX               NUMBER,
  IWJR              NUMBER,
  AGENT_DISCOUNT    NUMBER,
  EXTRA_COVER       NUMBER,
  NTA               NUMBER,
  SURCHARGE_FEE     NUMBER,
  INSENTIF          NUMBER,
  TOTAL             NUMBER,
  RADIO_ID          VARCHAR2(10 BYTE),
  CLASS_SEQUENCE    NUMBER
)
;


CREATE UNIQUE INDEX FLIGHT_CLASS_FARE_PK ON FLIGHT_CLASS_FARE
(CLASS_FARE_ID)
;

ALTER TABLE FLIGHT_CLASS_FARE ADD (
  CONSTRAINT FLIGHT_CLASS_FARE_PK
 PRIMARY KEY
 (CLASS_FARE_ID)
    USING INDEX 
);
