CREATE TABLE FLIGHTDETAILS
(
  FLIGHTDETID         VARCHAR2(40 BYTE),
  FLIGHTNUM           VARCHAR2(30 BYTE),
  ORIGIN              VARCHAR2(5 BYTE),
  DESTINATION         VARCHAR2(5 BYTE),
  DEP_TIME            DATE,
  ARR_TIME            DATE,
  PROMO_RATE          VARCHAR2(40 BYTE),
  ECONOMI_RATE        VARCHAR2(40 BYTE),
  BISNIS_RATE         VARCHAR2(40 BYTE),
  TRANSITID           VARCHAR2(50 BYTE),
  AIRLINE             VARCHAR2(40 BYTE),
  ISTRANSIT           CHAR(1 BYTE),
  DEPARTURE           VARCHAR2(5 BYTE),
  ARRIVAL             VARCHAR2(5 BYTE),
  CURRENCY            CHAR(10 BYTE),
  BASIC_RATE          NUMBER,
  IWJR                NUMBER,
  PAJAK               NUMBER,
  SURCHARGE_FEE       NUMBER,
  TAMBAHAN            NUMBER,
  BIAYA_ADMIN         NUMBER,
  BASIC_RATE_ECO      NUMBER,
  PAJAK_ECO           NUMBER,
  SURCHARGE_FEE_ECO   NUMBER,
  TAMBAHAN_ECO        NUMBER,
  BIAYA_ADMIN_ECO     NUMBER,
  BASIC_BISNIS        NUMBER,
  PAJAK_BISNIS        NUMBER,
  SURCHARGE_BISNIS    NUMBER,
  TAMBAHAN_BISNIS     NUMBER,
  ADMIN_BISNIS        NUMBER,
  INS_SERV_FEE_PROMO  NUMBER,
  FUEL_SERV_PROMO     NUMBER,
  INS_SERV_FEE_ECO    NUMBER,
  FUEL_SERV_ECO       NUMBER,
  INS_SERV_BIS        NUMBER,
  FUEL_SERV_BIS       NUMBER,
  LASTUPDATE          DATE                      DEFAULT SYSDATE,
  UPDATECODE          VARCHAR2(20 BYTE)
)
;

CREATE UNIQUE INDEX FLIGHTDETAILS_PK ON FLIGHTDETAILS
(FLIGHTDETID)
;
ALTER TABLE FLIGHTDETAILS ADD (
  CONSTRAINT FLIGHTDETAILS_PK
 PRIMARY KEY
 (FLIGHTDETID)
    USING INDEX 
);
