CREATE TABLE MST_AIRPORTS
(
  AIRPORT_ID    VARCHAR2(40 BYTE),
  AIRPORT_NAME  VARCHAR2(40 BYTE)               NOT NULL,
  AKA           VARCHAR2(20 BYTE),
  IATA          VARCHAR2(3 BYTE)                NOT NULL,
  ICAO          VARCHAR2(4 BYTE),
  CITY          VARCHAR2(30 BYTE),
  COUNTRY_ID    NUMBER,
  LATITUDE      VARCHAR2(20 BYTE),
  LONGITUDE     VARCHAR2(20 BYTE),
  ALTITUDE      VARCHAR2(5 BYTE),
  TIMEZONE      VARCHAR2(10 BYTE),
  DST           VARCHAR2(2 BYTE),
  AGENT_ID      NUMBER,
  CODEBYAGENT   VARCHAR2(15 BYTE)
)
;
CREATE UNIQUE INDEX MST_AIRPORTS_PK ON MST_AIRPORTS
(AIRPORT_ID)
NOLOGGING
;

ALTER TABLE MST_AIRPORTS ADD (
  CONSTRAINT MST_AIRPORTS_PK
 PRIMARY KEY
 (AIRPORT_ID)
    USING INDEX 
);
