CREATE TABLE MST_COUNTRIES
(
  COUNTRY_ID     NUMBER                         NOT NULL,
  COUNTRY_NAME   VARCHAR2(50 BYTE)              NOT NULL,
  COUNTRY_CODE   VARCHAR2(3 BYTE),
  REGION_ID      NUMBER,
  CAPITAL        VARCHAR2(40 BYTE),
  CURRENCY_CODE  VARCHAR2(3 BYTE),
  CURRENCY_NAME  VARCHAR2(20 BYTE)
)
;

CREATE UNIQUE INDEX MST_COUNTRIES_PK ON MST_COUNTRIES
(COUNTRY_ID)
LOGGING
;

ALTER TABLE MST_COUNTRIES ADD (
  CONSTRAINT MST_COUNTRIES_PK
 PRIMARY KEY
 (COUNTRY_ID)
    USING INDEX 
);


