CREATE TABLE MST_NATIONALITY
(
  CODE  VARCHAR2(2 BYTE)  NOT NULL,
  NAME  VARCHAR2(60 BYTE) NOT NULL
)
;

CREATE UNIQUE INDEX MST_NATIONALITY_PK ON MST_NATIONALITY
(CODE)
;

ALTER TABLE MST_NATIONALITY ADD (
  CONSTRAINT MST_NATIONALITY_PK
 PRIMARY KEY
 (CODE)
    USING INDEX 
);
