CREATE TABLE MST_AIRLINES
(
  AIRLINE_ID     NUMBER                         NOT NULL,
  NAMA           VARCHAR2(40 BYTE)              NOT NULL,
  CODE           VARCHAR2(3 BYTE)               NOT NULL,
  HQ             VARCHAR2(255 BYTE),
  COUNTRYID      NUMBER,
  WEBSITE1       VARCHAR2(255 BYTE),
  WEBSITE2       VARCHAR2(255 BYTE),
  WEBSITE3       VARCHAR2(255 BYTE),
  CALL_CENTER    VARCHAR2(20 BYTE),
  PHONE1         VARCHAR2(20 BYTE),
  PHONE2         VARCHAR2(20 BYTE),
  PHONE3         VARCHAR2(20 BYTE),
  EMAIL1         VARCHAR2(100 BYTE),
  EMAIL2         VARCHAR2(100 BYTE),
  INACTIVE       CHAR(1 BYTE),
  INACTIVE_DATE  DATE,
  LASTUPDATE     DATE
)
;

CREATE UNIQUE INDEX AIRLINES_PK ON MST_AIRLINES
(AIRLINE_ID)
NOLOGGING
;
ALTER TABLE MST_AIRLINES ADD (
  CONSTRAINT AIRLINES_PK
 PRIMARY KEY
 (AIRLINE_ID)
    USING INDEX 
 );
