SET DEFINE OFF;
Insert into MST_COUNTRIES
   (COUNTRY_ID, COUNTRY_NAME, COUNTRY_CODE, CAPITAL, CURRENCY_CODE, CURRENCY_NAME)
 Values
   (62, 'INDONESIA', 'ID', 'JAKARTA', 'IDR', 'RUPIAH');
Insert into MST_COUNTRIES
   (COUNTRY_ID, COUNTRY_NAME, COUNTRY_CODE, CAPITAL, CURRENCY_CODE, CURRENCY_NAME)
 Values
   (65, 'SINGAPORE', 'SG', 'SINGAPORE', 'SGD', 'DOLLAR');
Insert into MST_COUNTRIES
   (COUNTRY_ID, COUNTRY_NAME, COUNTRY_CODE, CAPITAL, CURRENCY_CODE, CURRENCY_NAME)
 Values
   (60, 'MALAYSIA', 'MY', 'KUALA LUMPUR', 'MYR', 'RINGGIT');
Insert into MST_COUNTRIES
   (COUNTRY_ID, COUNTRY_NAME, COUNTRY_CODE, CAPITAL, CURRENCY_CODE, CURRENCY_NAME)
 Values
   (66, 'THAILAND', 'TH', 'BANGKOK', 'THB', 'BAHT');
COMMIT;
