CREATE TABLE MST_HOTELS
(
  HOTEL_ID       VARCHAR2(40 BYTE),
  HOTEL_NAME     VARCHAR2(100 BYTE)             NOT NULL,
  COUNTRY_ID     NUMBER,
  ADDRESS1       VARCHAR2(100 BYTE),
  ADDRESS2       VARCHAR2(50 BYTE),
  CITY           VARCHAR2(30 BYTE),
  STATECODE      VARCHAR2(3 BYTE),
  ZIPCODE        VARCHAR2(15 BYTE),
  WEBSITE1       VARCHAR2(255 BYTE),
  WEBSITE2       VARCHAR2(255 BYTE),
  WEBSITE3       VARCHAR2(255 BYTE),
  PHONE1         VARCHAR2(30 BYTE),
  PHONE2         VARCHAR2(20 BYTE),
  PHONE3         VARCHAR2(20 BYTE),
  EMAIL1         VARCHAR2(100 BYTE),
  EMAIL2         VARCHAR2(100 BYTE),
  LATITUDE       VARCHAR2(20 BYTE),
  LONGITUDE      VARCHAR2(20 BYTE),
  AIRPORT_ID     NUMBER,
  STAR           VARCHAR2(6 BYTE),
  CATEGORY       VARCHAR2(1 BYTE),
  CHECKINTIME    VARCHAR2(10 BYTE),
  CHECKOUTTIME   VARCHAR2(10 BYTE),
  HIGH_RATE      VARCHAR2(10 BYTE),
  LOW_RATE       VARCHAR2(10 BYTE),
  CONFIDENCE     NUMBER,
  LOCATION       VARCHAR2(80 BYTE),
  INACTIVE       CHAR(1 BYTE),
  INACTIVE_DATE  DATE,
  AGENT_ID       NUMBER,
  CODEBYAGENT    VARCHAR2(15 BYTE),
  FAX            VARCHAR2(30 BYTE),
  PICBYAGENT     VARCHAR2(50 BYTE),
  REMARKS        VARCHAR2(255 BYTE),
  LASTUPDATE     DATE
)
;

CREATE UNIQUE INDEX MST_HOTELS_PK ON MST_HOTELS
(HOTEL_ID)
LOGGING
;
ALTER TABLE MST_HOTELS ADD (
  CONSTRAINT MST_HOTELS_PK
 PRIMARY KEY
 (HOTEL_ID)
    USING INDEX 
);
