CREATE TABLE MST_AGENTS
(
  AGENT_ID       NUMBER                         NOT NULL,
  AGENT_NAME     VARCHAR2(40 BYTE),
  ADDRESS1       VARCHAR2(100 BYTE),
  ADDRESS2       VARCHAR2(50 BYTE),
  CITY           VARCHAR2(30 BYTE),
  STATECODE      VARCHAR2(3 BYTE),
  ZIPCODE        VARCHAR2(15 BYTE),
  COUNTRY_ID     NUMBER,
  WEBSITE1       VARCHAR2(255 BYTE),
  WEBSITE2       VARCHAR2(255 BYTE),
  WEBSITE3       VARCHAR2(255 BYTE),
  PHONE1         VARCHAR2(20 BYTE),
  PHONE2         VARCHAR2(20 BYTE),
  PHONE3         VARCHAR2(20 BYTE),
  FAX1           VARCHAR2(20 BYTE),
  FAX2           VARCHAR2(20 BYTE),
  EMAIL1         VARCHAR2(100 BYTE),
  EMAIL2         VARCHAR2(100 BYTE),
  NPWP           VARCHAR2(20 BYTE),
  LATITUDE       VARCHAR2(20 BYTE),
  LONGITUDE      VARCHAR2(20 BYTE),
  INACTIVE       CHAR(1 BYTE),
  INACTIVE_DATE  DATE,
  LASTUPDATE     DATE,
  USERNAME       VARCHAR2(100 BYTE),
  PASSWORD       VARCHAR2(255 BYTE)
)
;
CREATE UNIQUE INDEX MST_AGENTS_PK ON MST_AGENTS
(AGENT_ID)
;
ALTER TABLE MST_AGENTS ADD (
  CONSTRAINT MST_AGENTS_PK
 PRIMARY KEY
 (AGENT_ID)
    USING INDEX 
);
