<%@ include file="/common/taglibs.jsp"%>
<head>
<title>Travel Insurance</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<link rel="stylesheet" href="styles/bootstrap.css" />
<link rel="stylesheet" href="styles/style.css" />
<style>
	.table-striped > tbody > tr:nth-child(2n+1) > td, .table-striped > tbody > tr:nth-child(2n+1) > th {
		background-color: #FFFFCC;
	}
</style>
</head>
<body style="padding-top: 20px; background: #B9FAAF">

<div>
  <div id="tv-topbar"> <a href="http://www.ppu.co.id/">
    <div id="tv-slim-logo"></div>
  </a></div>
  <div id="policyContainer" xmlns="http://www.w3.org/1999/html">
    <h1>SYARAT PENGGUNAAN</h1>
    <p> PERSYARATAN DAN KETENTUAN DI BAWAH INI WAJIB DIBACA SEBELUM          MENGGUNAKAN SITUS INI. PENGGUNAAN SITUS INI BERARTI PENERIMAAN DAN          PENUNDUKAN DIRI TERHADAP SYARAT DAN KETENTUAN YANG ADA DI BAWAH INI. </p>
    <p> Penggunaan situs www.berleha.com (&quot;Situs&quot;), yang dikelola oleh PT. Berleha (&ldquo;Kami&rdquo;),          adalah berdasarkan penerimaan dan penundukan terhadap Syarat dan Ketentuan          Penggunaan di bawah ini termasuk namun tidak terbatas pada Kerahasiaan, FAQs , dan          judul judul lainnya yang menjadi suatu bagian tak terpisahkan dari Syarat dan Ketentuan          dan termasuk di dalamnya referensi dan istilah yang digunakan (&quot;Syarat&quot;). Syarat ini dapat          kami ubah, modifikasi, tambah dan hapus sewaktu-waktu tanpa pemberitahuan. Syarat          wajib secara berkala dibaca. Dengan melanjutkan penggunaan Situs ini setelah perubahan          yang ada pada Syarat, berarti pengunjung, pengguna, Pengguna Terdaftar (&ldquo;Anda&rdquo; atau          &ldquo;Pengguna&rdquo;) menyatakan setuju dan sepakat terhadap perubahan yang ada. Apabila Anda          menggunakan jasa lain milik Kami, maka penggunaan Anda akan berdasarkan penundukan          terhadap Syarat dan Ketentuan yang berlaku bagi jasa tersebut. </p>
    <h2>1. HAK INTELEKTUAL PROPERTI</h2>
    <p> Segala Hak Kekayaan Intelektual yang ada di dalam Situs ini adalah kepunyaan dari          Berleha. Semua informasi dan bahan-bahan, termasuk tetapi tidak terbatas pada,          perangkat lunak, teks, data, grafik, gambar, suara, video, logo, ikon atau kode-kode          html dan kode-kode lain yang ada di website ini dilarang dipublikasikan, dimodifikasi,          disalin, digandakan atau diubah dengan cara apapun di luar area Situs ini tanpa izin          dari Berleha. Pelanggaran terhadap hak-hak Situs ini dapat ditindak sesuai dengan          peraturan yang berlaku. </p>
    <h2>2. TAUTAN DAN KONTEN</h2>
    <p> Situs dapat memuat tautan ke situs yang dioperasikan oleh pihak-pihak selain Berleha.          Tautan-tautan tersebut disediakan hanya sebagai referensi untuk Anda. Kami tidak          mengendalikan situs ataupun tautan tersebut dan tidak bertanggung jawab atas isi atau          privasi maupun praktek-praktek lain dari situs tersebut. Selanjutnya, tidak ada pihak          yang menjamin keakuratan atau kelengkapan informasi atau konten pada tautan yang          disertakan pada Situs. </p>
    <p> Kami, atau pihak ketiga lainnya, dapat memuat hasil pencarian otomatis atau          menyediakan tautan/link kepada situs lain. Kami dapat menyediakan kesempatan          bagi pihak ketiga untuk menyampaikan, memuat, mengirimkan atau menyediakan          informasi, data, tulisan, foto, suara, grafis, video, pesan, review, atau bahan lainnya          (&ldquo;Konten&rdquo;) melalui Situs ini. Kami tidak mereview dan/atau tidak memiliki kontrol terhadap          situs, sumber, dan Konten, Anda dengan ini menyatakan menerima bahwa Kami tidak          bertanggung jawab terhadap Konten yang ada, atau ketersediaan situs dan sumber          tersebut, dan kami tidak mendukung atau menyarankan dan tidak bertanggung jawab          atas situs atau asal muasal Konten. Anda dengan ini menyatakan sepakat untuk          melepaskan Kami dari dan terhadap setiap dan seluruh kewajiban, tanggungan baik          secara langsung ataupun tidak langsung, atas kerugian, kerusakan, yang diakibatkan          atau dituduhkan sebagai akibat dari atau sehubungan dengan penggunaan atau          dipertanggungjawabkannya suatu Konten, situs atau sumber. </p>
    <h2>3. LARANGAN PENGGUNAAN</h2>
    <p> Anda dengan ini sepakat untuk tidak menggunakan Situs atau Konten ini untuk hal          yang melawan hukum atau aktivitas tanpa izin, Anda sepakat bahwa Anda tidak akan          menggunakan peralatan, perangkat lunak, atau teknologi lain yang dapat menghalangi          atau berupaya untuk menghalangi cara kerja Situs ini. Anda sepakat untuk tidak          menggunakan Situs ini atau Kontennya untuk tujuan komersial. Anda sepakat untuk tidak          mengupayakan, membuat atau mengupayakan, mencari, mengutus agen otomatis atau          teknologi bentuk lainnya untuk mengumpulkan, mendapatkan, atau hal lainnya untuk          berinteraksi dengan Situs ini. </p>
    <h2>4. TIDAK ADA PENJAMINAN.</h2>
    <p> ANDA DENGAN INI MENYATAKAN SEPAKAT DAN SETUJU BAHWA SEJAUH MANA   DIIZINKAN OLEH PERATURAN YANG BERLAKU: (a) JASA DAN KONTEN DARI SITUS   INI DISEDIAKAN DENGAN KETENTUAN &ldquo;SEBAGAIMANA ADANYA&rdquo; DAN &ldquo;SEBAGAIMANA   TERSEDIA&rdquo;. KAMI DENGAN INI MENYATAKAN DENGAN TEGAS BAHWA KAMI TIDAK   MELAKUKAN PENJAMINAN ATAU GARANSI APAPUN BAIK SECARA TEGAS MAUPUN   TERSIRAT, SEHUBUNGAN DENGAN DAPAT DIPERDAGANGKAN SUATU PRODUK ATAU JASA,   ATAU KESIAPAN SUATU PRODUK DAN JASA YANG KAMI SEDIAKAN UNTUK SUATU   TUJUAN TERTENTU DAN TERHADAP PELANGGARAN YANG BERLAKU; (b) KAMI TIDAK   MENJAMIN BAHWA (i) FUNGSI DAN JASA YANG DISEDIAKAN DARI SITUS INI AKAN   BEBAS DARI GANGGUAN ATAU KESALAHAN APAPUN TERMASUK KEAMANAN DARI SITUS   INI; (ii) KELALAIAN AKAN DI PERBAIKI; ATAU (iii) SITUS INI ATAU SERVER   YANG MENYEDIAKAN JASA BEBAS DARI VIRUS ATAU KOMPONEN MEMBAHAYAKAN; (c)   KAMI TIDAK MENJAMIN MENGENAI KETEPATAN, KEASLIAN, INTEGRITAS ATAU   KUALITAS DARI KONTEN, SITUS ATAU SUMBER YANG ADA PADA DAN DARI SITUS,   TERMASUK, NAMUN TIDAK TERBATAS PADA PENJAMINAN KONTEN, SITUS ATAU SUMBER   YANG BEBAS DARI BAHAN YANG DAPAT MENYERANG, TIDAK SENONOH, ATAU DAPAT   DIPERDEBATKAN; (d) TIAP BAHAN YANG DIUNDUH ATAU DIPEROLEH MELALUI   PENGGUNAAN JASA INI ADALAH TANGGUNGJAWAB DAN RISIKO ANDA SENDIRI. ANDA   AKAN BERTANGGUNGJAWAB SEPENUHNYA TERHADAP KERUSAKAN SISTEM KOMPUTER ATAU   KEHILANGAN DATA YANG DIAKIBATKAN DARI PENGUNDUHAN MATERI YANG ADA. </p>
    <h2>5. PEMBATASAN PERTANGGUNGJAWABAN.</h2>
    <p>KAMI TIDAK AKAN BERTANGGUNGJAWAB TERHADAP KERUSAKAN DARI   PENGGUNAAN SITUS INI BAIK SECARA LANGSUNG MAUPUN TIDAK LANGSUNG, BAIK   KHUSUS ATAU TAMBAHAN SEBAGAI PENGGUNAAN SITUS INI ATAU PENGGUNAAN DARI   TAUTAN YANG ADA PADA SITUS WALAUPUN KAMI TELAH DIBERITAHU MENGENAI   KEMUNGKINAN KERUGIAN ATAU KERUSAKAN YANG DAPAT TERJADI. PERBAIKAN YANG   DAPAT DIBERIKAN PADA ANDA ADALAH PEMBERHENTIAN DARI PENGGUNAAN SITUS   INI. </p>
    <h2>6. INDEMNIFIKASI</h2>
    <p> Anda dengan ini menyatakan sepakat untuk membebaskan dan melepaskan Berleha,          karyawan, afiliasi, staf, partner, dari dan terhadap setiap dan seluruh tuntutan atau          permintaan, termasuk biaya konsultan hukum yang wajar, yang muncul sebagai akibat          tuntutan pihak ketiga sehubungan dengan penggunaan Situs; Konten yang diberikan,          disediakan melalui Situs ini; pelanggaran terhadap Syarat; dan/atau pelanggaran          terhadap hak atau kewajiban lain. </p>
    <h2>7. LINGKUP PENYEDIAAN JASA</h2>
    <p> Melalui Situs, Berleha menyediakan platform online di mana Anda dapat menelusuri          berbagai jenis maskapai, Agen Travel dan/atau akomodasi sementara dan penginapan          (sebagaimana berlaku), dan membuat pemesanan (merujuk kepada Pasal 15).          Dengan melakukan pemesanan melalui Situs, Anda dapat melakukan pemesanan          baik secara langsung melalui tautan langsung Agen Travel yang kami berikan atau          mengklik langsung tautan maskapai atau melakukan pemesanan melalui Situs dengan          menggunakan jasa Kami (melalui mitra dan/atau partner yang ada dan tersedia). Kami          akan memberikan konfirmasi pemesanan melalui konfirmasi e-mail. Kami berhak          untuk menolak pemesanan seperti yang ditetapkan di bawah ini. Dengan melakukan          pemesanan melalui Situs kami, maka Agen Travel terkait bertanggungjawab untuk          menerbitkan pemesanan Anda. </p>
    <p> Meskipun kami akan menggunakan keahlian kami dengan hati-hati   dalam melaksanakan jasa, kami tidak akan melakukan verifikasi, dan tidak   dapat menjamin bahwa, semua informasi yang diberikan adalah akurat,   lengkap, benar atau terbaru, dan kami tidak dapat bertanggung jawab atas   segala kesalahan (termasuk penempatan dan kesalahan pengetikan),   halangan (entah karena salah (sementara dan / atau sebagian), kerusakan,   perbaikan, peningkatan atau perbaikan Situs atau hal lainnya), ketidak   tepatan, penyesatan atau kesalahan informasi atau tidak terkirimnya   informasi. Tiap Agen Travel wajib bertanggung jawab secara langsung   setiap saat sehubungan dengan ketepatan, kelengkapan dan kebenaran   informasi pemesanan dan penerbitan terhadap pemesanan yang ada. </p>
    <p>Perubahan keadaan atau situasi pasar yang terjadi dapat   mengakibatkan perubahan dalam waktu singkat sehingga informasi yang   diberikan menjadi tidak tepat  atau tidak berlaku. Dalam hal terjadi   masalah, maka pelayan pelanggan dapat mengupayakan untuk membantu Anda   dan melayani untuk menghubungkan dengan Agen Travel terkait. </p>
    <p>Situs ini tidak mewakili dan tidak dapat dianggap sebagai suatu   rekomendasi atau penyaranan dari (tingkat kualitas pelayanan atau   rating) dari Agen Travel yang dicantumkan dalam Situs. Kami dengan ini   menyatakan penyangkalan terhadap pernyataan, penjaminan atau pembelaan   sehubungan dengan kualitas, status atau pemadaian dari Agen Travel yang   ada Situs. Agen Travel mungkin dapat dimasukan dalam bentuk kelas-kelas   yang berbeda berdasarkan review, rating dan hal lainnya. Rating yang ada   diberikan berdasarkan alogaritma otomatis yang dapat diperbaharui dan   diubah sewaktu-waktu. </p>
    <p>Kami memiliki hak untuk tidak menerima pengguna atau pemesanan   (atau dalam hal-hal tertentu membatalkan konfirmasi pemesanan) atas   diskresi Kami dan untuk alasan apapun tanpa perlu memberikan alasan   penolakan/pembatalan yang ada. Alasan utama penolakan pelanggan atau   pemesanan termasuk namun tidak terbatas pada; pelanggaran Syarat, sanksi   perdagangan atau ekonomis, embargo, larangan peraturan, penipuan atau   pencurian (atau indikasi maupun kecurigaan terhadapnya), sangkaan   tindakan kriminal, pemesanan yang mencurigakan, penyampaian oleh   pelanggan dalam hal kesalahan atau penyesatan informasi, masalah kartu   kredit, prilaku tidak pantas, ancaman, hinaan, penolakan untuk   memberikan informasi, halangan praktis, masalah komunikasi, kesalahan   nyata (selanjutnya diatur di bawah), riwayat, dimasukan dalam daftar   hitam oleh pemerintah atau organisasi internasional. Dalam hal pemesanan   ditolak atau dibatalkan oleh Berleha dan pembayaran telah dilakukan,   maka Anda akan menerima pengembalian dari total pemesanan yang telah   dilakukan. Kami dapat sewaktu-waktu menghapus atau menghilangkan   (&ldquo;Dihapus&rdquo;) keanggotaan dari Pengguna Situs ini, baik untuk sementara   atau untuk selamanya. Pengguna yang Dihapus tidak boleh melakukan   percobaan penggunaan Situs dalam nama lain atau melalui Pengguna lainnya   (selanjutnya diatur dalam Mekanisme Pencegahan Penipuan). </p>
    <p>Dalam suatu kasus tertentu, Kami dapat melakukan pembatalan   atau penolakan pemesanan sehubungan dengan &ldquo;kesalahan nyata&rdquo;, yang tidak   tergantung dari mana kesalahan itu berasal. Untuk lebih jelas, bahwa   kesalahan nyata adalah suatu kesalahan pada Situs (contohnya dalam hal   harga) di mana orang sewajarnya tidak akan menganggap hal tersebut   sebagai hal biasa. Jumlah yang dibebankan atau perbedaannya akan tetap   ditagihkan, dan Berleha memiliki hak diskresi untuk menolak atau   membatalkan pemesanan ini. </p>
    <p>Keadaan seperti adanya renovasi, kesalahan pemesanan, dan permintaan khusus pelanggan wajib diberitahukan kepada Agen Travel. </p>
    <h2>8. RATING</h2>
    <p> Rating yang ada hanya disediakan untuk informasi bagi Pengguna saja, dan rating yang            ada diberikan berdasarkan informasi dari supplier dan pelanggan. Kami tidak melakukan            verifikasi terhadap rating yang diberikan dan oleh karenanya tidak bertanggungjawab            atas kebenaran rating yang ada. </p>
    <h2>9. PENGGUNAAN SITUS</h2>
    <p>Berleha dengan ini memberikan Pengguna suatu hak yang   tertentu yang terbatas, tidak dapat dialihkan atau dipindahtangankan,   untuk mengakses dan menggunakan Situs sejauh mana diperbolehkan dengan   tegas oleh Syarat. Sehubungan dengan lisensi terbatas, Kami dengan tegas   menyatakan tidak memberikan hak atau lisensi sehubungan dengan   penggunaan Situs; hak atau lisensi yang tidak dengan tegas diberikan,   dimiliki sepenuhnya oleh Berleha atau pihak ketiga lainnya pemilik   lisensi tersebut. Konten yang ada pada Situs, berikut juga perangkat   lunak, infrastruktur yang digunakan untuk menyediakan Konten, sepenuhnya   dimiliki oleh Berleha atau supplier dan penyedianya, termasuk namun   tidak terbatas pada Agen Travel dan Maskapai Penerbangan atau Hotel   (sebagaimana berlaku). Anda dapat menggunakan Situs untuk melakukan   pemesanan dan Anda dengan ini menyatakan menjamin bahwa Anda tidak akan   melakukan pemesanan palsu atau spekulatif terhadap antisipasi permintaan   pemesanan yang mungkin ada. Anda dengan ini menyatakan menjamin bahwa   informasi pembayaran yang Anda berikan pada Kami adalah benar, tepat dan   akurat sepenuhnya. Anda  juga menyatakan menjamin untuk menyediakan   alamat surat elektronik, alamat surat-menyurat dan/atau rincian    informasi yang dapat dihubungi yang tepat dan akurat.</p>
    <p>Sehubungan dengan persyaratan penggunaan Situs, Anda sepakat   untuk tidak menggunakan Situs atau Konten untuk tujuan komersial atau   baik secara langsung atau tidak untuk selain keperluan pribadi atau   untuk tujuan yang melawan hukum, dilarang oleh hukum atau perbuatan yang   melanggar Syarat. Kecuali dengan persetujuan tertulis dari Berleha,   Anda sepakat untuk tidak mengubah, menyalin, membagikan, mengirimkan,   menampilkan, melaksanakan, mereproduksi, mengumumkan, mengizinkan,   mencipatakan kreasi derivatif dari, mengalihkan, atau menjual atau   menjual kembali tiap informasi, perangkat lunak, produk atau jasa yang   diperoleh sehubungan dengan Situs. Sebagai tambahan, Anda sepakat untuk   tidak: </p>
    <ol>
      <li>menggunakan Situs ini atau Konten untuk tujuan komersial tanpa seizin Berleha;</li>
      <li>mengakses, mengawasi atau menyalain tiap Konten dalam Situs   menggunakan teknologi, perangkat lunak, program apapun baik secara   manual ataupun otomatis untuk tujuan lain tanpa izin tegas tertulis dari   Berleha; </li>
      <li>melakukan tindakan yang mengakibatkan atau dapat mengakibatkan, suatu beban yang tidak wajar pada infrastruktur Kami; </li>
      <li>membuat suatu tautan utama bagi Situs (termasuk namun tidak   terbatas pada jalur pemesanan) untuk tujuan apapun tanpa persetujuan   tertulis Berleha; </li>
      <li>menjual kembali, menggunakan, menyalin, melakukan pengawasan   (contoh memasang spider, scrape), menampilkan, mengunduh atau melakukan   produksi tiap Konten, perangkat lunak, produk, jasa yang tersedia dalam   Situs untuk tujuan komersil atau tujuan/kegiatan persaingan usaha; </li>
      <li>melakukan percontohan (&ldquo;frame&rdquo; atau &ldquo;mirror&rdquo;) atau   mendirikan bagian dari Situs ini pada Situs web lainnya tanpa   persetujuan tertulis terlebih dahulu; </li>
      <li>mengirimkan suatu pengumuman kepada atau melalui Situs yang   melawan hukum berdasarkan hukum peraturan yang berlaku, ataupun   pengumuman yang dapat mendukung kegiatan criminal; </li>
      <li>mengirimkan atau menyediakan tautan kepada atau pengumuman   yang mengandung suatu materi yang dapat dianggap membahayakan, cabul,   berbau pornografi, tidak senonoh, berbau kekerasan, rasis, diskriminasi,   penghinaan, pengancaman, pelecehan, penindasan, kebencian atau tidak   pantas; </li>
      <li>mengirimkan atau menyediakan tautan kepada tiap pengumuman yang mengandung hal pencemaran nama baik, fitnah, dan kebohongan; </li>
      <li>mengirimkan atau melakukan pengumuman yang dapat melanggar   dan menyalahi hak intelektual property atau hak lainnya dari badan atau   orang tertentu termasuk namun tidak terbatas pada hak cipta, hak paten,   hak merek, rahasia dagang, kerahasiaan, atau publikasi;</li>
      <li>mengirimkan pengumuman yang mana dilarang oleh hukum yang   berlaku atau melanggar hak dan kewajiban yang ada berdasarkan hubungan   kontrak; </li>
      <li>meniru orang atau badan atau memalsukan keadaan atau   memberikan gambaran yang salah terhadap suatu afiliasi akan seseorang   atau badan atau mengambil identitas palsu apabila tujuannya adalah untuk   menyesatkan, membohongi atau menipu; </li>
      <li>memanipulasi, memalsukan dengan tujuan menyamarkan asal dari pengumuman yang  Anda berikan; </li>
      <li>menggunakan Situs ini dengan cara yang dapat merusak,   melumpuhkan, menghalangi, atau mengganggu penggunaan Situs atau pengguna   peralatan computer lainnya, atau mengakibatkan kerusakan, gangguan atau   membatasi fungsi dari perangkat lunak, perangkat keras atau peralatan   telekomunikasi; </li>
      <li>mencoba untuk mendapatkan akses terhadap penggunaan yang   tidak sah atas Situs atau Situs web terkait lainnya, akun lain, system   computer, jaringan yang terhubung dengan Situs melalui hacking,   pencurian kata sandi atau hal serupa lainnya; </li>
      <li>mendapatkan atau berupaya mendapatkan materi atau informasi   melalui cara-cara yang bukan sengaja disediakan oleh Situs (termasuk   namun tidak terbatas tujuan lain penyediaan oleh Situs), termasuk namun   tidak terbatas dalam mendapatkan atau mengumpulkan informasi tentang   pihak lainnya seperti alamat email; </li>
      <li>terlibat dalam tindakan penipuan atau tindakan yang   ditujukan untuk memanipulasi suatu engine pencarian halaman (SERP) atau   mempekerjakan engine pencarian optimal (SEO) yang dianggap bertentangan   dengan engine pencarian umumnya. Praktek SEO dianggap suatu tindakan   yang tidak etis atau &ldquo;spamdexing&rdquo; termasuk namun tidak terbatas pada    penyelubungan, meta data, tag judul, scraping konten, skema link, bom   google, pencarian kata kunci, text tersembunyi atau tautan tersembunyi,   skema tautan, komentar mengandung spam dan hal lainnya; atau </li>
      <li>melakukan tindakan lainnya yang dapat mengakibatkan   kerusakan pada Situs, Berleha atau afiliasinya dan termasuk   karyawannya, reputasi Berleha atau hal lain yang dapat menimbulkan   dampak negatif. </li>
    </ol>
    <p>Kecuali ditentukan dengan tegas sebaliknya, Situs web tidak   diperbolehkan melakukan tautan kepada halaman lainnya selain daripada   halaman utama Situs atau frame Situs atau halaman web atau bahan yang   ada didalamnya, atau melakukan tautan terhadap aspek Situs dalam bentuk   email dengan tujuan komersil tanpa mendapatkan persetujuan tertulis yang   tegas oleh Berleha.</p>
    <p>Dengan melakukan pemesanan melalui Situs, Anda dengan ini   menyatakan dan menjamin bahwa Anda tidak dalam keadaan dilarang atau   dibatasi oleh program sanksi apapun.</p>
    <h2>10. HARGA, TAMBAHAN BIAYA dan Promo</h2>
    <p> </p>
    <h2>A. HARGA dan Promo</h2>
    <p>Harga yang lebih rendah hanya tersedia pada waktu tertentu dan   pada Agen Travel tertentu, namun harga tersebut memiliki persyaratan   yang berbeda misalnya sehubungan dengan pemesanan dan kebijakan   pengembalian.</p>
    <h2>B. Tambahan Biaya</h2>
    <p>Tiap harga yang tertera pada Situs hanya tersedia dengan   persyaratan tertentu dan memungkinkan adanya perubahan yang terjadi   tergantung pada ketersediaan pemesanan, jangka waktu dan/atau kuota.   Harga yang tersedia dapat termasuk pajak dan tambahan biaya lainnya lagi   namun dalam hal dan keadaan tertentu dapat juga tidak termasuk pajak   dan biaya jasa, Pengguna diharapkan untuk memperhatikan total biaya yang   harus dibayarkan berikut perinciannya pada saat konfirmasi dikirimkan   kepada email Pengguna.  Pengguna diharapkan untuk memverifikasi   pemesanan pada lembar pemesanan; Pengguna dapat membatalkan pemesanan   setiap saat sebelum konfirmasi terakhir dilakukan. Harga yang tertera   akan dirinci sehingga Pengguna dapat melihat jumlah yang harus dibayar,   tiap tambahan biaya dikarenakan penggunaan kartu kredit atau biaya yang   dikenakan antar bank karena pengiriman biaya akan dikenakan kepada   Pengguna dan apabila terdapat kekurangan dalam jumlah yang dibayarkan   maka Berleha dapat memberikan email notifikasi mengenai kekurangan   jumlah yang harus dibayarkan oleh Pengguna. Dalam hal dalam jangka waktu   yang diberikan Pengguna masih belum juga membayarkan kekurangan biaya   yang ada maka Pengguna dianggap membatalkan pemesanan, Berleha dapat   melakukan pengembalian dalam jumlah penuh atau mengembalikan jumlah yang   telah dipotong dengan biaya yang dikeluarkan oleh Berleha sebagai   akibat dari tidak dibayarnya biaya kekurangan tersebut oleh Pengguna   dalam jangka waktu sesuai prosedur yang ditentukan oleh Berleha.   Apabila terdapat keraguan mengenai jasa dan pelayanan maka Pengguna   dapat menghubungi layanan pelanggan Berleha (selama jam operasioanl   layanan pelanggan yang ditentukan oleh Berleha). Kami bukan pihak yang   memungut pajak, tiap pungutan dan pembebanan pajak akan ditanggung oleh   Agen Travel atau Pengguna tergantung dari jenis pajak dan pungutan   sesuai dengan peraturan yang berlaku </p>
    <h2>C. Mata Uang</h2>
    <p>Pembayaran dilakukan dalam mata uang rupiah, dengan jumlah   sesuai dengan yang tertera tanpa penanggungan biaya bank atau biaya   lainnya oleh Berleha. </p>
    <h2>11. KERAHASIAAN</h2>
    <p> Kami akan berupaya menjaga kerahasiaan Anda. Kebijakan Kerahasiaan akan diatur lebih lanjut dalam di bawah.</p>
    <h2>12. KARTU KREDIT-PEMBAYARAN-PENIPUAN</h2>
    <p>Untuk pembayaran Pemesanan melalui Situs, kartu kredit Anda   akan ditagih oleh Berleha untuk harga penuh (pengembalian dana yang   terjadi tergantung pada kondisi Pemesanan yang ada) pada saat pemesanan   dan konfirmasi pemesanan. Silakan memeriksa detail pemesanan secara   menyeluruh untuk setiap saat tersebut sebelum Anda membuat pemesanan.   Berleha akan memproses pengembalian uang, sebagaimana berlaku, dalam   jangka waktu yang wajar. Untuk pemesanan tertentu, Berleha tidak akan   menagih kartu kredit Anda, karena Anda diwajibkan untuk membayar vendor   terkait langsung. Dalam rangka menjaga dan mengenkripsi informasi kartu   kredit Anda ketika dalam perjalanan ke kita, kita menggunakan &quot;Secure   Socket Layer (SSL)&quot; teknologi untuk layanan kami. </p>
    <p>Dalam hal penipuan kartu kredit atau penggunaan yang tidak sah   dari kartu kredit Anda oleh pihak ketiga, Anda harus menghubungi bank   atau penerbit kartu segera setelah menyadari penggunaan yang tidak sah   tersebut. Jika Anda mencurigai adanya pemesanan yang tidak sah atau   penipuan yang dilakukan melalui Berleha, silakan hubungi tim Layanan   Pelanggan kami segera. </p>
    <p>Untuk melakukan pemesanan Anda harus berusia lebih dari 18   tahun dan memiliki kapasitas hukum penuh untuk membuat transaksi (atau   memiliki otorisasi dari wali hukum Anda ). Anda wajib menggunakan kartu   kredit atau debit milik Anda sendiri dan memastikan bahwa ada dana yang   cukup untuk menutupi biaya transaksi. Anda menerima tanggung jawab   keuangan untuk semua transaksi yang dilakukan atas nama Anda atau akun   Anda.</p>
    <p>Anda wajib memastikan bahwa rincian Anda berikan kepada Kami   dengan dalam membuat pemesanan sepenuhnya adalah benar, tepat dan   akurat. Berleha berhak untuk tidak menerima kartu kredit tertentu.   Berleha dapat menambah atau menghapus metode pembayaran lainnya dengan   kebijakannya sendiri. </p>
    <p>Dalam kasus tertentu, kami mungkin membutuhkan informasi   tambahan atau verifikasi untuk memvalidasi dan mengkonfirmasi pemesanan,   seperti yang dijelaskan secara lebih rinci di Situs. Pemesanan tidak   dikonfirmasi sampai Anda telah menerima email konfirmasi dengan voucher   dan ada kemungkinan bahwa vendor dapat melaksanakan  pemeriksaan   penipuan selama pemesanan diproses, dalam hal penipuan terjadi maka   pemesanan tidak akan lagi tersedia atau otomatis menjadi batal.   Berleha tidak dapat dimintai pertanggungjawaban dalam kasus tersebut.   Jika Anda memilih untuk tidak menyampaikan informasi tambahan, pemesanan   tidak akan selesai dan sepenuhnya menjadi batal. </p>
    <h2>13.PERSYARATAN PEMESANAN – PEMBATALAN– PERMINTAAN TERTENTU</h2>
    <p>Dengan melakukan pemesanan melalui Situs, Anda dengan ini   menyatakan sepakat untuk menerima persyaratan dan ketentuan dari Agen   Travel, Hotel atau Maskapai yang ada, termasuk sehubungan dengan   kebijakan mengenai pembatalan dan/atau tidak hadirnya Pengguna atau   pelanggan berikut sehubungan dengan permintaan tertentu oleh Pengguna   yang mungkin akan diberikan oleh Agen Travel atau Hotel atau Maskapai   tersebut. Berleha tidak bertanggung jawab atas  hal pelanggaran Syarat   dan Ketentuan yang dimiliki oleh pihak ketiga (hotel, maskapai, agen   travel dan lainnya) atau ketersediaan atas permintaan tertentu Pengguna.</p>
    <p> </p>
    <p>Sehubungan dengan pembatalan yang dilakukan Pengguna, maka   Berleha mungkin akan dapat menahan atau mengambil bagian dari jumlah   yang dibayarkan untuk mengganti biaya yang telah dikeluarkan sehubungan   dengan pembatalan yang terjadi. </p>
    <p>Pengguna diharapkan membaca dan mengerti Syarat dan Ketentuan yang ada pada hotel, maskapai penerbangan dan Agen Travel.</p>
    <p>Permintaan Khusus: Dalam hal terdapat permintaan khusus   sehubungan dengan pemesanan (contohnya kamar dapat dengan mudah diakses   dengan kursi roda, bantuan kursi roda pada saat pengantaran tiket,   perubahan nama, perubahan tanggal, perubahan penulisan nama, penambahan   poin), maka Pengguna dapat menghubungi langsung Agen Travel yang ada,   dan permintaan tersebut akan berdasarkan ketersediaan dan peraturan   maskapai, Agen Travel atau Hotel yang ada (sebagaimana  berlaku). </p>
    <h2>14. HAK INTELEKTUAL PROPERTI</h2>
    <p>Nama domain, Situs, logo, dan hak intelektual property lainnya   dimiliki sepenuhnya oleh Berleha dan/atau afiliasinya. Produk lain dan   nama perusahaan yang ada ada pada Situs adalah nama, merek dagang,   merek, tanda jasa, logo, symbol atau design lainnya (&ldquo;Hak Intelektual   Properti&rdquo;) milik Berleha atau perusahaan asosiasi atau pihak ketiga   lainnya. Penggunaan atas Hak Intelektual Properti yang ada pada Situs,   tidak dapat dianggap sebagai rekomendasi atau sponsor bagi Situs oleh   pihak ketiga tersebut. Berleha memiki hak cipta atas Situs, dan Anda   dilarang menggunakan Hak Intelektual Properti tanpa persetujuan   Berleha.</p>
    <p>Situs dapat mengandung materi Hak Intelektual Properti termasuk   namun tidak terbatas pada tulisan, perangkat lunak, foto, grafis dan   mungkin video, music dan suara. Keseluruhan dari Konten Situs dilindungi    oleh undang-undang hak cipta. Kami dan para pemegang lisensi memiliki   hak cipta dan/atau hak lainnya atas pemilihan, koordinasi, pengaturan,   dan perbaikan Konten berikut konten asal yang ada. Anda dilarang untuk   mengubah, menampilkan, mempublikasikan, mengeksploitasi ikut serta dalam   suatu tindakan penjualan atas Konten dan konten asalnya, baik secara   keseluruhan atau sebagian kecuali dinyatakan sebaliknya dengan tegas   dalam Syarat ini. </p>
    <p>Kecuali ditentukan sebaliknya, maka perangkat lunak yang   diperlukan bagi penyediaan jasa atau tersedia untuk digunakan pada Situs   dan Hak Intelektual Properti dalam Konten pada Situs dimiliki oleh   Berleha, afiliasinya atau perusahaan asosiasinya, pemberi izin,   supplier dan penyedia Konten. Berleha tidak bertanggung jawab atas Hak   Intelektual yang disediakan oleh pihak ketiga atau atas pelanggaran Hak   Intelektual Properti milik pihak ketiga tersebut. </p>
    <p>Anda dapat menggunakan informasi dalam Situs hanya untuk   penggunaan pribadi non komersil. Kecuali ditentukan sebaliknya dan   diperbolehkan secara tegas oleh undang-undang hak cipta, maka Pengguna   dilarang menyalin, membagikan ulang, mentransmisi ulang, mempublikasi   atau melakukan tindakan eksploitasi komersial dari pengunduhan yang   dilakukan tanpa seizin pemilik Hak Intelektual Properti tersebut. Dalam   hal Pengguna telah mendapatkan izin yang diperlukan maka Pengguna   dilarang melakukan perubahan atau penghapusan. Pengguna dengan ini   menyatakan menerima dan mengetahui bahwa dengan mengunduh materi Hak   Intelektual Properti bukan berarti mendapatkan hak kepemilikan atas   pengunduhan materi Hak Intelektual Properti tersebut. </p>
    <p>Kami dapat menyediakan tautan kedalam Situs lain yang dikelola   oleh pihak lain, dengan mengklik tautan tersebut Pengguna dengan ini   menyatakan mengetahui dan setuju bahwa tindakan tersebut adalah tindakan   yang dilakukan atas tanggung jawab pribadi Pengguna yang telah dengan   sukarela memasuki situs lain bukan berada dalam pengawasan dan   tanggungjawab Berleha.</p>
    <p>Berleha dalam membuat Situs berikut penyusunan source code   dan perangkat lunak pendukung, dapat menggunakan lisensi dari pihak   ketiga lainnya baik berupa open source (GNU/GPL) dan telah terdapat   modifikasi yang merupakan milik kepunyaan Berleha. Setiap penggunaan   dari open source dan Hak Intelektual Properti milik pihak ketiga telah   mendapatkan ijin yang diperlukan. </p>
    <h2>Tuntutan atas Pelanggaran Hak Intelektual Properti </h2>
    <p>Apabila terdapat bukti pelanggaran Hak Intelektual Properti   Anda dilanggar maka Anda atau wakil Anda (&ldquo;Pengirim&rdquo;) dapat mengirimkan   surat pemberitahuan berisi hal berikut di bawah ini: </p>
    <ol>
      <li>Nama dan alamat Pengirim; </li>
      <li>Dalam hal Pengirim bukan pemilik Hak Intelektual Properti   atau lisensi eksklusif maka wajib mencantumkan nama dan alamat pemilik   Hak Intelktual Properti; </li>
      <li>Dalam hal terdapat alamat pengirim bukan berasal dari Indonesia, maka wajib mengirimkan alamat sementara di Indonesia; </li>
      <li>Nomor telepon, faksimili (apabila ada) dan alamat surat elektronik yang dapat dihubungi; </li>
      <li>Rincian yang secukupnya sehingga dapat membuktikan adanya Hak Intelktual Properti yang dilanggar; </li>
      <li>Rincian yang secukupnya sehingga dapat mengenali dan   mendapatkan adanya Hak Intelktual Properti yang dilanggar termasuk   alamat online dari kopi elektronik yang ada;</li>
      <li>Pernyataan Pengirim untuk menghapuskan atau melumpuhkan akses kepada salinan elektronik yang dilanggar tersebut; </li>
      <li>Pernyataan bahwa Pengirim dengan itikad baik mengenali adanya pelanggaran sebagaimana dikenali pada angka 5 Pasal ini; </li>
      <li>Pernyataan dalam pemberitahuan bahwa informasi yang diberikan adalah akurat; </li>
      <li>Pernyataan bahwa Pengirim adalah (a) pemilik atau pemegang   hak eksklusif atas Hak Intelektual Properti yang dilanggar tersebut;   atau (b) kuasa yang sah untuk bertindak atas pemilik atau pemegang hak   eksklusif tersebut; dan</li>
      <li>Pernyataan bahwa Pengirim tunduk pada Hukum Indonesia dan   memilih forum hukum Mediasi pada Pusat Mediasi Nasional yang ditunjuk   dan disediakan oleh Berleha apabila terjadi sengketa berdasarkan   Undang-Undang Hak atas Intelektual Properti.</li>
    </ol>
    <p>Surat tersebut wajib ditandatangani oleh Pengirim dan dikirimkan secara fisik dan melalui email ke alamat berikut ini:</p>
    <p> <span id="address">PT Berleha Inovasi Global<br />
      Ruko Theta Paramount L16<br />
      Gading Serpong, Tangerang</span></p>
    <p>Kami akan mereview dan menangani pemberitahuan yang sesuai   dengan persyaratan di atas dan sesuai dengan peraturan Hukum Indonesia   yang berlaku. </p>
    <p>Kami menyarankan Anda untuk mengkonsultansikan dulu sebelum   tuntutan dikirimkan, dan Anda dengan ini menyatakan bertanggung jawab   secara pribadi atas kerugian atau kerusakan yang mungkin terjadi sebagai   akibat pemalsuan atau tuduhan palsu pelanggaran Hak Intelektual   Properti. </p>
    <p>Ketentuan dalam pasal ini juga berlaku dalam hal tuntutan,   perselisihan, persengketaan, dan penafsiran yang timbul dari dan atas   penggunaan Situs dan pelaksanaan Syarat. </p>
    <h2>15. REVIEW/ULASAN – KORESPONDENSI – HAK KONTEN PENGGUNA</h2>
    <p>Dengan melengkapi pemesanan, Anda dengan ini menyatakan sepakat   untuk menerima surat elektronik berisi ajakan untuk mengisi   ulasan/konten review sehubungan dengan pemilihan Agen Travel, Maskapai,   dan Hotel. Penampilan korespondensi atas review adalah diskresi   Berleha semata-mata. Berleha dapat menampilkan korespondensi berisi   tentang komentar, tingkat pelayanan dan nama pelanggan terkait. Anda   dengan ini menyatakan menerima dan menyetujui untuk tunduk dalam Syarat   dan Ketentuan review yang ada. Anda dengan ini menyatakan sepakat untuk   menjamin bahwa (i) Anda memiliki dan menguasai semua hak atas review   yang Anda berikan kepada Situs; (ii) konten review tersebut adalah   akurat dan tidak mengandung penyesatan; dan (iii) penggunaan atau   penampilan atau transmisi dari konten review tersebut tidak melanggar   Syarat atau hukum peraturan yang berlaku dan Anda tidak mengakibatkan   pelanggaran hak apapun atau menyebabkan cidera pihak manapun. Anda   dengan ini memberikan hak kepada Berleha untuk bertindak apabila   terdapat pihak yang melanggar hak Anda atau hak Berleha sehubungan   dengan pelanggaran konten review dan Syarat yang ada. Anda dengan ini   menyatakan bertanggung jawab secara pribadi atas konten review yang Anda   berikan atau sampaikan. </p>
    <p>Konten review yang diberikan akan dianggap bukan merupakan   informasi rahasia dan Berleha tidak memiliki kewajiban untuk   memperlakukan konten review sebagai suatu informasi rahasia atau suatu   kepemilikan. Tanpa membatasi Ketentuan yang ada dalam Syarat, Berleha   memiliki hak untuk menggunakan konten review sebagaimana dinilai patut   termasuk namun tidak terbatas pada penghapusan, pemotongan, pengubahan,   penolakan untuk menampilkan. Berleha tidak memiliki kewajiban untuk   membayar konten review yang Anda sampaikan, termasuk namun tidak   terbatas pada konten review yang diubah, dihapuskan, dipotong dan   diubah. Berleha tidak memiliki kewajiban untuk memberikan atau   mencantumkan atau mengumumkan penulis atau pihak ketiga lainnya. </p>
    <p>Dalam kondisi apapun, Pengguna dengan ini menyatakan bahwa   sehubungan dengan konten review (a) Anda tidak membutuhkan atribusi atau   pengenalan dalamnya ataupun dalam pekerjaan derivatifnya termasuk dalam   perbaikan atau perbaharuan yang ada didalamnya (b) Anda tidak keberatan   dalam pemublikasian, penggunaan, penghapusan, pengubahan,   pengeksploitasian konten review yang dilakukan Berleha, karyawan,   pengganti dan penerima pengalihannya; (c) Anda dengan ini melepaskan hak   tuntut dan sepakat untuk tidak menuntut hak apapun dalam konten review;   dan (d) Anda dengan ini menyatakan melepaskan dan membebaskan   Berleha, karyawan, afiliasi, pemegang hak, pengganti, dan penerima   pengalihan dari tuntutan apapun sehubungan dengan konten review. </p>
    <h2>16. SARAN BERPERGIAN</h2>
    <p>Dengan menampilkan berbagai tempat tujuan, Berleha dengan ini   tidak menjamin bahwa perjalanan yang Anda lakukan bebas dari risiko   apapun dan Berleha tidak dapat dimintai pertanggungjawaban apapun   sehubungan dengan kerugian atau kerusakan yang diakibatkan dari   perjalanan ke tempat tujuan tersebut. Berleha dalam keadaan dan   kondisi apapun tidak dapat dimintai pertanggungjawaban dalam hal insiden   yang terjadi baik dalam perjalanan ataupun selama Anda berada dalam   tempat tujuan. Anda bertanggung jawab secara pribadi atas pemilihan   perjalanan, rute perjalanan dan tempat tujuan selama perjalanan Anda   berlangsung. Berleha tidak dapat dimintai pertanggungjawaban atas   kehilangan yang terjadi apabila Pengguna gagal membawa passport atau   kartu tanda penduduk yang diperlukan untuk melangsungkan perjalanan   Anda. </p>
    <h2>17. TATA CARA PEMESANAN DAN PEMBAYARAN</h2>
    <p>Situs memberikan pelayanan pada Pengguna melalui penggunaan jasa Berleha sebagai berikut ini:</p>
    <p> </p>
    <ol>
      <li>Layanan Pemesanan. Pengguna dapat menggunakan layanan Situs   untuk melakukan pemesanan terhadap pilihan Agen Travel yang ada. Dalam   hal Agen Travel gagal dalam menerbitkan pemesanan maka Agen Travel akan   bertanggung jawab atas kegagalan penerbitan tersebut dengan memberikan   ganti rugi yang setimpal dan Berleha tidak bertanggung jawab atas   pengembalian atau pembayaran ganti rugi tersebut. Berleha akan   membantu sebagai bentuk itikad baik kepedulian Berleha, namun Pengguna   dengan ini menyatakan membebaskan Berleha dari dan terhadap segala   jenis kerugian, tuntutan kerusakan atau ganti rugi yang mungkin timbul   baik sehubungan dengan rusaknya sistem, gangguan sistem atau koneksi   baik dari Pihak Agen Travel maupun Pengguna, kelalaian Agen Travel   maupun Pengguna dan hal lain diluar kuasa Berleha. </li>
      <li>Tautan situs. Pengguna dapat memilih untuk memesan langsung   kepada Agen Travel/Hotel/Maskapai (&ldquo;Vendor&rdquo;) yang ada, dengan mengklik   tombol tautan yang ada pada Situs  atau langsung memesan atau   menghubungi Vendor langsung  untuk melakukan pemesanan. Berleha tidak   bertanggung jawab untuk melakukan perbantuan apapun sehubungan dengan   pemesanan langsung. Pengguna dengan ini menyatakan untuk membebaskan dan   melepaskan Berleha dari dan terhadap segala jenis tuntutan kerugian,   bunga dan biaya atas pemesanan langsung yang dilakukan oleh Pengguna,   dan Berleha berhak menolak memberikan jasa bantuan atau   menindaklanjuti permintaan Pengguna yang melakukan pemesanan langsung   kepada Vendor terkait. </li>
    </ol>
    <h2>Tata Cara Pembayaran</h2>
    <p>Semua bentuk pemesanan yang sudah dilakukan harus dilakukan   pembayarannya dalam waktu 1 (satu) jam, jika pembayaran tidak   dilaksanakan, maka pihak Berleha  berhak membatalkan semua pemesanan   tersebut atau tidak melanjutkan/memproses pemesanan tersebut. </p>
    <p>Pembayaran pemesanan dalam dapat dilakukan dengan Transfer,   Kartu Kredit, dan Paypal. Pembayaran dengan menggunakan transfer antar   bank, mengharuskan pengguna untuk melampirkan struk tanda bukti transfer   sebagai tanda bukti pelunasan pemesanan yang sudah dipesan melalui   email konfirmasi yang dikirim oleh Berleha. Untuk selanjutnya pengguna   mengikuti prosedur yang tertera pada email tersebut. </p>
    <p>Pembayaran dengan Kartu Kredit dan Paypal untuk selanjutnya dapat dilakukan dengan mengikuti prosedur-prosedur yang tersedia. </p>
    <p>Penerbitan Kode Pemesanan bagi Pengguna Layanan Situs Berleha </p>
    <p>Setelah dilunasinya pembayaran, pihak Berleha akan melakukan pemesanan dan menerbitkan kode pemesanan disertai dengan:</p>
    <ol>
      <li>Kode Pemesanan</li>
      <li>Nama Pelanggan</li>
      <li>Jumlah Pemesanan</li>
      <li>Detail Pemesanan</li>
      <li>Nama Agen Travel</li>
      <li>Alamat Agen Travel</li>
      <li>Nomor Telp./Extension</li>
      <li>Nama/Hp. Pihak Agen</li>
    </ol>
    <p>Pihak Agen Travel akan segera menerbitkan pemesanan selama jam   kerja/jam operasional yang dimiliki oleh Agen  Travel dalam waktu tidak   lebih dari 2(dua) hari kerja. Pemesanan akan dikirim dalam bentuk email   ke Pengguna sesuai dengan email yang dicantumkan. </p>
    <h2>18. KETENTUAN LAINNYA</h2>
    <p>Berleha tidak mengelola atau mengendalikan Hotel, Maskapai   ataupun Agen Travel. Agen Travel, Hotel, dan Maskapai yang bersangkutan   bertanggung jawab secara langsung atas Pengguna.</p>
    <p>Anda dengan ini menyatakan sepakat untuk membebaskan dan   melepaskan Berleha dari dan terhadap segala jenis tanggungan,   kerusakan, atau kerugian termasuk biaya hukum yang diperlukan oleh   Berleha sehubungan dengan tindakan, tidak dilaksanakannya suatu   kewajiban atau pelanggaran  yang Anda lakukan. Apabila penggunaan Situs   ini adalah untuk kepentingan pihak ketiga (&ldquo;Pihak Lain&rdquo;), berupa anggota   keluarga atau teman seperjalanan, maka Anda bertanggung jawab atas   ketepatan informasi yang disediakan untuk digunakan. Anda memiliki   kewajiban untuk memberitahukan mengenai Syarat yang berlaku kepada Pihak   Lain tersebut. Tiap Pengguna yang menggunakan Situs ini untuk dan atas   nama Pihak Lain dengan ini menyatakan sepakat untuk melepaskan dan   membebaskan Berleha dari dan terhadap semua bentuk dan jenis   pertanggungjawaban kerugian, tuntutan dan biaya (termasuk namun tidak   terbatas pada biaya pembelaan), sehubungan dengan Pihak Lain atau   kegagalan Pengguna untuk memenuhi semua kewajiban yang telah dinyatakan   dalam Situs dan Syarat. </p>
    <p>Anda wajib mematuhi semua peraturan perundangan yang berlaku   dan Berleha tidak dapat dimintai pertanggungjawaban atas   ketidaktahuan, kelalaian atau pelanggaran Pengguna maupun Pihak Lain. </p>
    <p>Bahasa yang berlaku bagi penerapan Situs dan Syarat ini adalah bahasa Indonesia. </p>
    <p>Dalam hal terdapat satu atau bagian dari Syarat ini yang tidak   dapat dilaksanakan atau menjadi batal maka ketentuan tersebut tidak akan   mempengaruhi berlakunya ketentuan lain dalam Syarat ini dan ketentuan   lainnya tersebut akan tetap berlaku sejauh mana diperbolehkan oleh   Peraturan Perundangan. Ketentuan yang tidak dapat berlaku atau batal   akan digantikan dengan ketentuan yang baru dengan mempertimbangkan   tujuan utama dari diberikannya ketentuan awal. </p>
    <p>Berleha memiliki hak diskresi untuk mengubah, menangguhkan,   memberhentikan Situs dan/atau bagian dari Situs, termasuk jasa atau   produk yang tersedia dalam Situs, dan/atau penggunaan Situs, atau bagian   darinya, tiap saat untuk alasan apapun tanpa melakukan pemberitahuan   kepada Anda. </p>
    <p>Dalam hal terdapat pemutusan, maka Anda akan tetap terikat pada   kewajiban yang tertera dalam Syarat termasuk tiap penjaminan dan   pelepasan berikut juga tiap penyampingan dan pembatasan tanggung jawab   yang telah diterima oleh Anda.</p>
    <p>Berleha juga tidak bertanggung jawab atas Anda atau pihak   ketiga lainnya sehubungan dengan pemutusan akses Anda kepada Situs.   Berleha memilik hak untuk mengubah dan mencabut ketentuan Syarat (atau   bagian darinya) yang dianggap patut.</p>
    <p>Kegagalan dalam melaksanakan hak Berleha bukan merupakan   pengesampingan atau pelepasan dari hak terkait atau hak berikutnya. Anda   tidak diperbolehkan untuk mengalihkan atau memberikan hak Anda kepada   pihak lain. Kami dapat mengubah Syarat sewaktu-waktu dengan menampilkan   perubahan pada Situs.  Versi terbaru dari Syarat akan berlaku melampau   versi yang telah lampau atau yang pernah ditampilkan sebelumnya. </p>
    <h2>19. FORCE MAJEURE</h2>
    <p>Berleha tidak bertanggung jawab atas segala kegagalan   transaksi yang mengakibatkan kerugian di pihak Pengguna yang diakibatkan   karena Force Majeure. Kondisi yang dikategorikan sebagai Force Majeure   adalah bencana alam (banjir, gempa bumi), epidemik, kerusuhan,   pernyataan perang, perang, embargo, perubahan peraturan yang berlaku,   petir, angina topan, mogok buruh, demonstrasi, kebangkrutan maskapai,   dan sebagainya.</p>
    <p>Jika dalam kasus Force Majeure Berleha tidak dapat memproses   pesanan Anda, Berleha tidak akan bertanggung jawab atas kerugian yang   disebabkan dengan cara apapun. </p>
    <h2>20. TENTANG Berleha - FAQs</h2>
    <p>Setiap jasa disediakan oleh PT. Berleha, yaitu suatu   perseroan terbatas yang didirikan berdasarkan hukum Republik Indonesia,   memiliki domisili di Jakarta Barat.</p>
    <p>Apabila Anda memiliki pertanyaan lebih lanjut silakan merujuk pada <a href="http://www.Berleha.com/faq">FAQs</a>.</p>
  </div>
</div>
<div id="miniFooter">
  <p>© PT Berjaya Inovasi Global 2015</p>
</div>
<div id="qtip-rcontainer"></div>
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="stmgwb2" align="right" height="1" width="1">
  <embed src="https://mpsnare.iesnare.com/stmgwb2.swf" name="stmgwb2" swliveconnect="true" allowscriptaccess="always" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" height="1" width="1"></embed>
</object>
</body>
 